//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

namespace AntHill
{
	public class Tasks
	{
		public const int IDLE = 0;
		public const int SEARCH = 1;
		public const int OPTIMIZEPATH = 2;
		public const int COLLECT = 3;


		public Tasks ()
		{
		}
	}
}

