//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using System;
using UnityEngine;

namespace AntHill
{
	public class Food
	{
		public Path path;
		public bool isEmpty = false;
		public GameObject foodObject;
		
		public Food ()
		{
		}
	}
}